
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int IDENT = 13;
  public static final int IFSYM = 8;
  public static final int LBRA = 6;
  public static final int ELSESYM = 9;
  public static final int PREFIX = 10;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int STRINGL = 12;
  public static final int RBRA = 7;
  public static final int error = 1;
  public static final int COM = 2;
  public static final int RPAREN = 5;
  public static final int SUFFIX = 11;
  public static final int LPAREN = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COM",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "LBRA",
  "RBRA",
  "IFSYM",
  "ELSESYM",
  "PREFIX",
  "SUFFIX",
  "STRINGL",
  "IDENT"
  };
}

